using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace OOP_Laboration_3
{
    public struct RandomShit
    {
        public static Random rng = new Random();

        #region FestivalNames
        public static List<string> festivalNames = new List<string>()
        {
"Baltic Song Contest",
"Bluesfestival i Eslöv",
"Bonnarock",
"Svenska brassbandfestivalen",
"Bråvalla festival",
"Båstad kammarmusikfestival ",
"Clandestino Festival",
"Emmabodafestivalen",
"Festival Omodernt",
"Festspelen i Piteå ",
"Fighting The Darkness",
"Folk & Världsmusikgalan",
"Folkmusiknatta",
"Frizon",
"Fryksdalsdansen",
"Furuvik Reggae Festival",
"GAS-festivalen",
"Gatufesten",
"Getaway Rock Festival",
"Gotland Chamber Music Festival",
"Granny goes street",
"Gullbrannafestivalen",
"Göteborgs Jazzfestival",
"Hasslöfestivalen",
"Hultsfredsfestivalen",
"Hällevik Tradjazz Festival",
"JesusRock",
"Julitafestivalen",
"Kajrocken",
"Kalvfestivalen",
"Kaosfestivalen i Mellerud",
"Kapris",
"Keep It Loud",
"Kôrpehôlsfestivalen",
"Korrö folkmusikfestival",
"Kringelfestivalen",
"Kristianstad/Åhus Jazzfestival",
"Kuggnäsfestivalen",
"Körstämman i Skinnskatteberg",
"Laulun Laulut ",
"Linköpings folkmusikfestival",
"Ljusfesten",
"Luleå Hamnfestival",
"Lund Choral Festival",
"Lyckå Kammarmusik Festival",
"Make Musik Sthlm",
"Malungsfors visfestival",
"Metallsvenskan",
"Metaltown",
"Motaladagarna",
"Musik i Kullabygden",
"Musik vid Siljan",
"Mönsterås bluesfestival",
"New Media Meeting",
"Norbergfestival",
"Peace & Love",
"Pier Pressure",
"Popadelica",
"Putte i parken",
"Rock for Moc",
"Rock on the Docks",
"Rockslaget",
"Rockstad: Falun",
"Rookiefestivalen",
"Römppäviikko",
"Saxå kammarmusikfestival",
"Seasidefestivalen",
"Siesta!",
"Skogsröjet",
"Skulefestivalen",
"Skånes orgelveckor",
"Studentorkesterfestivalen",
"Stålboga sommaropera",
"Stöde Musikvecka",
"Summerburst",
"Svenska dansbandsveckan",
"Sweden Rock Cruise",
"Sweden Rock Festival",
"Sättralundsfesten",
"Söderslätts Countryfestival",
"The Island Festival",
"This is Hultsfred",
"Tivolirock",
"Tjörns visfestival",
"Torsåker Bluegrass Festival",
"Trästockfestivalen",
"Törebodafestivalen",
"Uport Musikweekend ",
"Urkult",
"Vadstena-Akademien",
"Viksholmsfestivalen",
"Virserums Musikdagar",
"Visfestivalen i Västervik",
"Way Out West",
"West Coast Riot ",
"Where's the Music?",
"Ydre Country Festival",
"Ystad Sweden Jazz Festival",
"Åmåls bluesfest",
"Äggstockfestivalen",
"Ölandsveckan"
        };

        #endregion

        #region FilmNames

        public static List<string> filmNames = new List<string>()
        {

"All the President's Men",
"All the Right Moves",
"Almost Famous",
"Almost Heroes",
"Along Came a Spider",
"Alpha Dog",
"Alpha and Omega",
"Alvin and the Chipmunks",
"Alvin and the Chipmunks: Chipwrecked",
"Alvin and the Chipmunks: The Road Chip",
"Man in the Moon, The",
"Man of the West",
"Man of the Year",
"Man on Fire",
"Man on the Moon",
"Man Who Fell To Earth",
"Man Who Shot Liberty Valance, The",
"Man Who Wasn't There, The",
"Man with Two Brains, The",
"Next",
"Next Karate Kid, The",
"Nice Dreams",
"Nicholas & Alexandra",
"Nick and Norah's Infinite Playlist",
"Night at the Museum",
"Open Water",
"Operation Dumbo Drop",
"Opposite of Sex, The",
"Orange County",
"Orgazmo",
"Original Sin",
"Orphan",
"Osmosis Jones",
"Other Boleyn Girl, The",
"Other Guys, The",
"Out of Sight",
"Out of the Past",
"Outbreak"
        };

        #endregion

        #region ConcertNames

        public static List<string> concertNames = new List<string>()
        {
"Aeon",
"Amon Amarth",
"Amaranthe",
"Angtoria ",
"Arch Enemy",
"Arckanum",
"At the Gates",
"Bathory",
"Beseech",
"Bloodbath",
"Bloodbound",
"Candlemass",
"Cemetary",
"Crashdïet",
"The Crown",
"Cult of Luna",
"Dan Swano",
"Dark Funeral",
"Dark Tranquillity",
"Darkane",
"Deathstars",
"Deranged",
"Diabolique",
"Dismember",
"Dissection",
"Dream Evil",
"Edge of Sanity",
"Entombed",
"Enforcer",
"Europe",
"Evergrey",
"Falconer",
"Ghost",
"Grave",
"HammerFall",
"Hardcore Superstar",
"Hypothermia",
"The Haunted",
"Hypocrisy",
"In Flames",
"In Mourning",
"Kaamos",
"Katatonia",
"Lake of Tears",
"Liers in Wait",
"Lifelover",
"Lord Belial",
"Yngwie Malmsteen",
"Marduk",
"Meshuggah",
"Månegarm ",
"Necrophobic",
"Nifelheim",
"Nightingale",
"Nocturnal Rites",
"October Tide",
"Opeth",
"Ophthalamia",
"PAIN",
"Pain of Salvation",
"The Project Hate MCMXCIX",
"Raubtier",
"Sabaton",
"Saint Deamon",
"Scar Symmetry",
"Seventh Wonder",
"Shining",
"Soilwork",
"Sonic Syndicate",
"Steelwing",
"Therion",
"Thyrfing",
"Tiamat",
"Unleashed",
"Watain",
"Witchery",
"Wolf",
"Valkyrja",
"Vildhjarta",
"Vintersorg",
"Vomitory",
"Zonaria"
        };

#endregion

    }
}